import { useCallback, useEffect, useRef, useState } from "react";
import { Button, Checkbox, Select, Typography } from "antd";
import PropTypes from "prop-types";
import { LineChart, Line, CartesianGrid, XAxis, YAxis, Legend, Tooltip, ResponsiveContainer } from "recharts";

const { Title } = Typography;

const CropWaterUseChart = ({cropETData}) => {

    const [showMethods, setShowMethods] = useState(false);
    const [selectedCrop, setSelectedCrop] = useState('');
    const [selectedCropOptions, setSelectedCropOptions] = useState([]);
    const [visibleLines, setVisibleLines] = useState({
        ETrs: true,
        ETa: true,
        Precipitation: true,
    });

    const  chartData = useRef([]);
    // get an array of chart codes

    const chartCropCodes = cropETData && cropETData.crop_codes ? cropETData.crop_codes : null;

    const getCropCodeValue = useCallback((cropCode) => {
        if (typeof cropCode === 'string') {
            return cropCode;
        }

        return cropCode?.value || cropCode?.label || '';
    }, []);

    const getCropCodeLabel = useCallback((cropCode) => {
        const codeValue = getCropCodeValue(cropCode);
        const cropName = cropETData?.crop_names?.[codeValue];

        return cropName ? `${cropName} (${codeValue})` : codeValue;
    }, [cropETData, getCropCodeValue]);

    const onSelectedCropChange = (value) => {
        // console.log("Selected crop:", value);
        // does the selected crop have associated data?  If so, set teh chartData to the data for that crop, otherwise set it to an empty array
        if (cropETData && cropETData.data) {
            chartData.current = cropETData.data[value] || [];
        }

        setSelectedCrop(value);
    }

    const toggleLineVisibility = (lineKey) => {
        setVisibleLines((current) => ({
            ...current,
            [lineKey]: !current[lineKey],
        }));
    };

    useEffect(() => {
        const _selectedCropOptions = chartCropCodes && Array.isArray(chartCropCodes)
            ? chartCropCodes.map((crop) => ({
                value: getCropCodeValue(crop),
                label: getCropCodeLabel(crop),
            }))
            : [];
        setSelectedCropOptions(_selectedCropOptions);

        if (!selectedCrop && chartCropCodes && Array.isArray(chartCropCodes) && chartCropCodes.length > 0) {
            setSelectedCrop(getCropCodeValue(chartCropCodes[0]));
        }
    }, [chartCropCodes, selectedCrop, getCropCodeLabel, getCropCodeValue]);

    useEffect(() => {
        if (cropETData && cropETData.data && selectedCrop) {
            chartData.current = cropETData.data[selectedCrop] || [];
        } else {
            chartData.current = [];
        }
    }, [cropETData, selectedCrop]);

    return (
        <div style={{ marginLeft: '1em' }}>
            <label htmlFor='selectCrop'>Select a crop from the list for crop-specific water use information: </label>
            
            <br/>
            <Select
                id='selectCrop'
                style={{ width: '20em', marginTop: '0.5em' }}
                showSearch
                placeholder="Select a crop"
                optionFilterProp="label"
                onChange={onSelectedCropChange}
                options={selectedCropOptions}
                value={selectedCrop}
            />
            <br />
            <div style={{ marginBottom: '0.75em' }}>
                <Checkbox checked={visibleLines.ETrs} onChange={() => toggleLineVisibility('ETrs')}>
                    Reference ET (ASCE-ESRI Alfalfa)
                </Checkbox>
                <Checkbox checked={visibleLines.ETa} onChange={() => toggleLineVisibility('ETa')} style={{ marginLeft: '1em' }}>
                    Actual ET
                </Checkbox>
                <Checkbox checked={visibleLines.Precipitation} onChange={() => toggleLineVisibility('Precipitation')} style={{ marginLeft: '1em' }}>
                    Precipitation
                </Checkbox>
            </div>
            {/* this chart is generated by
             1) getting the ET (Kimberely-Penman (in)), ETrs (ASCE-EWRI alfalfa), ETos (ASCE-EWRI grass), 
                MN (daily Tmin), MX (daily Tmax), PP (precipitation (in))) from 
                
             2)    
                */}
            <ResponsiveContainer width="100%" height={360} style={{ backgroundColor: '#fefefe' }}>
                {selectedCrop && selectedCrop !== '' ? (
                    <Title level={4} style={{ color: 'black', textAlign: 'center' }}>Crop Water Use - {selectedCrop}</Title>
                ) : (
                    <Title level={4} style={{ color: 'black', textAlign: 'center' }}>Crop Water Use</Title>
                )}
                <LineChart
                    width='100%'
                    data={chartData.current}
                    margin={{
                        top: 5,
                        right: 45,
                        left: 20,
                        bottom: 50,
                    }}
                >
                    {chartData.current && chartData.current.length > 0 && visibleLines.ETrs && (
                        <Line key='ETrs' name='Reference ET (ASCE-ESRI Alfalfa)' type="monotone" dataKey='ETrs'
                            formatter={(value) => value.toFixed(2)} unit=' in/day' stroke={"#202020"} dot={false} />
                    )}

                    {chartData.current && chartData.current.length > 0 && visibleLines.ETa && (
                        <Line key='ETa' name='Actual ET' type="monotone" dataKey={"ETa"}
                            formatter={(value) => value.toFixed(2)} unit=' in/day' stroke={"#2020EE"} dot={false} />
                    )}

                    {chartData.current && chartData.current.length > 0 && visibleLines.Precipitation && (
                        <Line key='Precipitation' name='Precipitation' type="monotone" dataKey={"Precipitation"}
                            formatter={(value) => value.toFixed(2)} unit=' in/day' stroke={"#EE2020"} dot={false} />
                    )}

                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="Date" type="category" allowDuplicatedCategory={false} name='Days' />
                    <YAxis label={{
                        value: `Crop Water Use - in/day`,
                        style: { textAnchor: 'middle' },
                        angle: -90,
                        position: 'left',
                        offset: 0,
                    }}
                    />
                    <Tooltip />
                    <Legend />
                </LineChart>
            </ResponsiveContainer>

            
            <ResponsiveContainer width="100%" height={360} style={{ backgroundColor: '#fefefe' }}>
                {selectedCrop && selectedCrop !== '' ? (
                    <Title level={4} style={{ color: 'black', textAlign: 'center' }}>Crop Coefficient (Kc) - {selectedCrop}</Title>
                ) : (
                    <Title level={4} style={{ color: 'black', textAlign: 'center' }}>Crop Coefficient (Kc)</Title>
                )}
                <LineChart
                    width='100%'
                    data={chartData.current}
                    margin={{
                        top: 5,
                        right: 45,
                        left: 20,
                        bottom: 50,
                    }}
                >
                    {chartData.current && chartData.current.length > 0 && (
                        <Line key='Kc' name='Crop Coefficient (Kc)' type="monotone" dataKey='Kc'
                            formatter={(value) => value.toFixed(2)} stroke={"#202020"} dot={false} />
                    )}

                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="Date" type="category" allowDuplicatedCategory={false} name='Days' />
                    <YAxis label={{
                        value: `Crop Coefficient (Kc)`,
                        style: { textAnchor: 'middle' },
                        angle: -90,
                        position: 'left',
                        offset: 0,
                    }}
                    />
                    <Tooltip />
                    <Legend />
                </LineChart>
            </ResponsiveContainer>

            <Button
                type="primary"
                style={{ marginTop: '0.75em', marginBottom: '0.75em' }}
                onClick={() => setShowMethods((current) => !current)}
            >
                {showMethods ? 'Hide Methods' : 'Show Methods'}
            </Button>

            {showMethods && (
                <div style={{ marginBottom: '1em', padding: '0.75em', border: '1px solid #d9d9d9', borderRadius: '6px'}}>
                    <strong>Methods</strong>
                    <p style={{ marginBottom: 0 }}>
                        This chart is generated using Agrimet data made availalbe on their website.  Specifically, the
                        
                        
                          from the station crop water use dataset passed in as `chartData`.
                        The selected crop determines which ETc series is plotted alongside the reference ET series,
                        and the chart only renders lines for data fields that exist in the current dataset.
                    </p>
                </div>
            )}

            <br />
        </div>
    );
};

export default CropWaterUseChart;

CropWaterUseChart.propTypes = {
    cropETData: PropTypes.shape({
        crop_codes: PropTypes.arrayOf(
            PropTypes.shape({
                value: PropTypes.string,
                label: PropTypes.string,
            })
        ),
        crop_names: PropTypes.object,
        data: PropTypes.object,
    }),
};