import { Form, Input, Button, Collapse, Divider } from 'antd';
import PropTypes from 'prop-types';

const Start = ({ setStart }) => {
    const onFinish = (values) => {
        // Placeholder: handle login logic here
        console.log('Login values:', values);
    };

    const handleRegister = () => {
        // Placeholder: handle registration logic or navigation here
        console.log('Navigate to registration or show registration form');
    };

    return (
        <>
           <Divider size='small'/>
           <div style={{ fontSize: "1rem" }}>
                <Collapse
                    bordered={false}
                    items={[
                        {
                            key: '1',
                            label: 'Overview of this Tool',
                            children: <p style={{color:'white'}}>The Crop Management System is a new tool developed by Oregon State University's
                                <a href='/agtap'> Ag Water team</a> to
                                assist growers in managing irrigation and fertilization for agricultural fields around the state.
                                It includes state of the art algorithms for estimating crop growth and yield for individual fields.
                                It allows you to track and manage crop growth, irrigation, and fertilization levels, provides
                                estimates of crop water status and yield, and helps you make informed decisions related to
                                irrigation and fertilization.
                            </p>
                        },
                        {
                            key: '2',
                            label: 'Getting Started',
                            children: <p style={{ color: 'white' }}>
                                To get started, we ask you to register an account with the Crop Management System and log in. We can not
                                "see" your password, so we suggest you store your login information in a secure location, preferably in a password manager.
                                the "New User? Register here" link below to create an account.

                                <br />
                                <br />
                                We also provide a "guest" login option that allows you to explore the system without
                                registering an account. This is a great way to see how the system works and
                                what it can do for you before committing to an account.
                            </p>
                        },
                        {
                            key: '3',
                            label: 'Data Privacy and Security',
                            children: <p style={{ color: 'white' }}>This tool is designed to help you manage your crops effectively while ensuring
                                the security and privacy of your data.  Smart crop management requires data, and this tools collects and stores information
                                about your cropping systems and fields.  We store this data for your convenience and to provide a history
                                of your management decisions to better inform the recommndations generated by this tool.
                                We take concerns about privacy and data security very seriously, and we will never share your data with anyone
                                without your explicit permission. Your data will never leave the secure server housed at Oregon State University.
                            </p>
                            
                        },
                        {
                            key: '4',
                            label: 'Feedback',
                            children: <p style={{ color: 'white' }}>
                                If you have questions or comments about this tool, please reach out to the
                                <a href='mailto:ag-water.oregonstate.edu'> Oregon State University Ag Water team.</a>.
                            </p>
                        }

                    ]}
                />

                <Divider size='small'/>

            </div>

            <div style={{ maxWidth: 350, margin: "2em auto" }}>
                <h3 style={{ textAlign: "center" }}>User Login</h3>
                <Form
                    name="login"
                    layout="vertical"
                    onFinish={onFinish}
                >
                    <Form.Item
                        label="Username"
                        name="username"
                        rules={[{ required: true, message: 'Please input your username!' }]}
                    >
                        <Input />
                    </Form.Item>

                    <Form.Item
                        label="Password"
                        name="password"
                        rules={[{ required: true, message: 'Please input your password!' }]}
                    >
                        <Input.Password />
                    </Form.Item>

                    <Form.Item>
                        <Button type="primary" htmlType="submit" block>
                            Log in
                        </Button>
                    </Form.Item>
                </Form>
                <div style={{ textAlign: "center", marginTop: 12 }}>
                    <Button type="link"
                        style={{
                            color: 'yellow'
                        }}
                        onClick = { handleRegister } >
                        New User? Register here
                    </Button>

                    <div style={{ textAlign: "center", fontSize: "1.2rem", marginTop: "1.5em" }}>
                        <Button type="primary" className='button' onClick={() => setStart(false)}>
                            Continue as Guest
                        </Button>
                    </div>


                </div>
            </div>

        </>
    );
};

Start.propTypes = {
    setStart: PropTypes.func.isRequired,
};

export default Start;