import React from 'react';

export default function DatasetModal({ isOpen, onClose }) {
    if (!isOpen) return null;

    return (
        <div className="modal-overlay" onClick={onClose} style={{
            position: 'fixed', top: 0, left: 0, width: '100%', height: '100%',
            backgroundColor: 'rgba(0,0,0,0.8)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 9999
        }}>
            <div className="modal-content card" onClick={(e) => e.stopPropagation()} style={{
                maxWidth: '800px', width: '90%', maxHeight: '80vh', overflowY: 'auto',
                backgroundColor: 'var(--bg-card)', color: 'var(--text-primary)', padding: '30px', borderRadius: '8px', 
                border: '2px solid var(--border-color)', position: 'relative'
            }}>
                <h2 style={{color: 'var(--accent-orange)', marginTop: 0}}>Dataset Details</h2>
                <p>Below is a summary of the 12 metrics displayed on the timeline chart, explaining what is measured and how the raw pixel/station data is aggregated into a single watershed (HUC-8) value.</p>
                
                <h3 style={{color: 'var(--accent-yellow)', borderBottom: '1px solid #333', paddingBottom: '5px'}}>☁️ Meteorological Indices</h3>
                <ul>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>USDM (US Drought Monitor):</strong> Official drought severity ratings, which use a continuous 0–5 numerical score derived from the basin percentage covered by each severity tier (D0-D4).</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>PDSI (Palmer Drought Severity Index):</strong> A gridded relative dryness metric physically combining temperature and precipitation, expressed as a weekly spatial average of grid cells falling inside the watershed boundary.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>SPI-3mo (3-Month Standardized Precipitation Index):</strong> A 3-month rolling comparison of precipitation against the historical normal, computed as a spatial average of GridMET pixels across the watershed.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>EDDI-1mo (1-Month Evaporative Demand Drought Index):</strong> A measurement of atmospheric "thirst" over the past month, represented by a spatial average of the weekly grid clipped to the watershed.</li>
                </ul>
                <p style={{fontSize: '0.85rem', color: '#999', marginTop: '-5px', marginBottom: '15px', paddingLeft: '10px', borderLeft: '3px solid #555'}}>
                    <strong>Note on Severity Units:</strong> The raw values for PDSI, SPI-3mo, and EDDI-1mo each follow different native scales (e.g., PDSI ranges roughly from -10 to +10; SPI and EDDI are Z-scores). The data pipeline converts each to a common 0–5 severity scale using percentile-based crosswalk tables that map each index's statistical distribution to USDM severity tiers (D0 through D4). After this conversion, all four meteorological indices share the same scale.
                </p>

                <h3 style={{color: '#38a169', borderBottom: '1px solid #333', paddingBottom: '5px'}}>🌾 Agricultural Indices</h3>
                <ul style={{color: '#fff'}}>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>VCI (Vegetation Condition Index):</strong> A metric derived from NASA MODIS satellite imagery reflecting relative vegetation greenness against historical best/worst cases, aggregated via a weekly spatial average of the 1km grid across the watershed.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>VHI (Vegetation Health Index):</strong> A hybrid metric blending VCI with thermal satellite readings to account for structural moisture and immediate temperature stress.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>CMI (Crop Moisture Index):</strong> An indicator of short-term agricultural topsoil moisture conditions generated by mathematically weighting recent precipitation and temperature.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>SSMI (Stand. Soil Moisture Index):</strong> A standardized historical Z-score derived from NASA SMAP satellite root-zone soil moisture.</li>
                </ul>

                <h3 style={{color: '#3182ce', borderBottom: '1px solid #333', paddingBottom: '5px'}}>💧 Hydrological Indices</h3>
                <ul style={{color: '#fff'}}>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>SWE % Normal (Snow Water Equivalent):</strong> Daily snow water content measurements (inches of water) derived from pressure-sensing snow pillows at SNOTEL stations physically located within the watershed.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>Streamflow Percentile:</strong> A historical percentile ranking of daily water discharge from physical USGS flow gauges located internally in the watershed.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>Forecast % Normal:</strong> NRCS seasonal water-supply volume forecasts generated for the upcoming summer season.</li>
                    <li style={{color: '#fff', marginBottom: '8px'}}><strong>SPI-1yr (1-Year Standardized Precipitation Index):</strong> A 12-month trailing precipitation metric highlighting long-term structural reservoir and groundwater recharge deficits.</li>
                </ul>

                <button 
                    onClick={onClose} 
                    style={{
                        marginTop: '20px', padding: '10px 20px', backgroundColor: 'var(--accent-orange)', 
                        color: '#000', border: 'none', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold'
                    }}>
                    Close
                </button>
            </div>
        </div>
    );
}
